SELECT MIDDLE.AUTHOR_ID, AUTHOR.AUTHOR_NAME,MIDDLE.CATEGORY, SUM(MIDDLE.TOTAL) as TOTAL_SALES
FROM(SELECT BOOK.BOOK_ID, BOOK.CATEGORY, BOOK.AUTHOR_ID,SUM(BOOK.PRICE * C.CNT) as TOTAL
FROM(SELECT BOOK_ID , SUM(SALES) as CNT 
FROM BOOK_SALES
WHERE SALES_DATE LIKE '2022-01%'
GROUP BY BOOK_ID) as C
INNER JOIN BOOK 
ON C.BOOK_ID = BOOK.BOOK_ID
GROUP BY C.BOOK_ID) as MIDDLE
INNER JOIN AUTHOR
ON MIDDLE.AUTHOR_ID = AUTHOR.AUTHOR_ID
GROUP BY MIDDLE.AUTHOR_ID,MIDDLE.CATEGORY 
ORDER BY AUTHOR.AUTHOR_ID ASC, MIDDLE.CATEGORY DESC
