-- 코드를 입력하세요
-- ONLINE_SALE // ONLINE_SALE_ID, USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
-- OFFLINE_SALE // OFFLINE_SALE_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') as SALES_DATE ,PRODUCT_ID , USER_ID , SALES_AMOUNT
FROM ONLINE_SALE
WHERE SALES_DATE LIKE '%-03-%'

union

SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') as  SALES_DATE , PRODUCT_ID, NULL as USER_ID  , SALES_AMOUNT
FROM OFFLINE_SALE
WHERE SALES_DATE LIKE '%-03-%'
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC , USER_ID ASC
