-- 코드를 입력하세요
SELECT YEAR(os.SALES_DATE) as YEAR, MONTH(os.SALES_DATE) as MONTH , ui.GENDER, count(DISTINCT ui.USER_ID) as USERS
FROM USER_INFO as ui
INNER JOIN ONLINE_SALE as os
ON ui.USER_ID = os.USER_ID
WHERE ui.GENDER IS NOT NULL
GROUP BY YEAR(os.SALES_DATE), MONTH(os.SALES_DATE) , ui.GENDER
ORDER BY YEAR(os.SALES_DATE), MONTH(os.SALES_DATE) , ui.GENDER