
-- 코드를 입력하세요
SELECT mp.MEMBER_NAME , rr.REVIEW_TEXT , DATE_FORMAT(rr.REVIEW_DATE,'%Y-%m-%d') as REVIEW_DATE
FROM REST_REVIEW as rr
INNER JOIN MEMBER_PROFILE as mp
ON rr.MEMBER_ID = mp.MEMBER_ID
WHERE rr.MEMBER_ID IN (SELECT MEMBER_ID FROM REST_REVIEW GROUP BY MEMBER_ID
HAVING COUNT(*) = (SELECT COUNT(*) 
                    FROM REST_REVIEW
                    GROUP BY MEMBER_ID
                    ORDER BY COUNT(*) DESC
                    LIMIT 1) )
ORDER BY REVIEW_DATE , rr.REVIEW_TEXT