SELECT MONTH(START_DATE) as MONTH , ori.CAR_ID, COUNT(*) as RECORDS
FROM(
SELECT CAR_ID, COUNT(CAR_ID) as count  
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE>= '2022-08-00' and START_DATE <= '2022-10-31'
GROUP BY CAR_ID
HAVING count>=5 
) as five
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY as ori
ON ori.CAR_ID = five.CAR_ID
WHERE START_DATE>= '2022-08-00' and START_DATE <= '2022-10-31'
GROUP BY ori.CAR_ID,MONTH(START_DATE)
HAVING RECORDS >=1
ORDER BY MONTH, CAR_ID DESC